ARG RUBY_IMAGE_TAG=3.2.1-alpine3.17
FROM docker.io/ruby:${RUBY_IMAGE_TAG}

ENV APP_HOME=/home/app
ENV HISTFILE=${APP_HOME}/.bash_history
ENV BUNDLE_PATH=${APP_HOME}/.bundle

RUN apk -U upgrade \
    && apk add curl git build-base gcompat \
       freetds-dev mariadb-dev 

WORKDIR ${APP_HOME}
